services:
  - type: web
    name: heures-caillet-ferblanterie
    env: node
    buildCommand: npm install
    startCommand: node server-postgres.js
    envVars:
      - key: NODE_ENV
        value: production
